[package]
name = "bird_binding_derive"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bird_binding = { git  = "https://github.com/ChousX/bird_binding.git" }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
